const language = {
  'Autocomplete.brands': 'Marki',
  'Autocomplete.categories': 'Kategorie',
  'Autocomplete.parts': 'Numer części',
  'Autocomplete.suggestions': 'Sugestie',
  'Availability.days': 'dni',
  'Availability.direct': 'Dostępna ilość: {quantity}',
  'Availability.failed': 'Operacja nie powiodła się',
  'Availability.notAvailable':
    'Tego produktu nie ma obecnie w magazynie, ale nadal można go zamówić. Dowiedz się o dokładnym czasie dostawy.',
  'Availability.orderStopTime': 'Zamów przed {time}',
  'Availability.show': 'Sprawdź dostępność',
  'Availability.showMoreOrders': '{quantity} więcej zamówień',
  'Availability.unknown': 'Określ czas dostawy przy {quantity}',
  'Availability.upcoming': '{quantity} za {numDays} {days}',
  'BasicHeader.backToWebshop': 'Powrót do webshop',
  'Footer.trademarkNoticeSDF':
    'Agricenter is a trademark of SDF. All rights reserved.',
  'CategoryMenu.mobile.goToPreviousCategory': 'Powrót do {category}',
  'CategoryMenu.mobile.modalTitle': 'Filtruj według kategorii',
  'CategoryMenu.mobile.previousCategory.default': 'Wszystkie kategorie',
  'CategoryMenu.mobile.selectCurrentCategory': 'Wszystko w {category}',
  'Disclaimer.deere.notApproved':
    'Niezatwierdzone przez inzynierów JOHN DEERE do uzytkowania ze sprzetem JOHN DEERE',
  'Disclaimer.deere.partAvailable':
    'Ten produkt jest dostepny za posrednictwem JDPoint',
  'Disclaimer.deere.exclusives':
    'Zwieksz obecnosc marki John Deere w twoim sklepie detalicznym JD Place i zamawiaj zabawki w opakowaniach John Deere wylacznie za posrednictwem JDPoint',
  'Disclaimer.deere.authorizedPart':
    'Autoryzowana czesc zamienna do sprzetu John Deere',
  'Disclaimer.sdf.notApproved':
    'Niezatwierdzone przez techników SDF do użytkowania ze sprzętem SDF',
  'ErrorPage.body': 'Prosimy spróbować później. Przepraszamy za niedogodności.',
  'ErrorPage.title': 'Operacja nie powiodła się',
  'footerNavigation.socialMedia': 'SOCIAL MEDIA',
  'Facets.categories.toggleButton.less': 'Pokaż mniej',
  'Facets.categories.toggleButton.more': 'Pokaż więcej',
  'form.error.required': 'Wymagane',
  'form.optional': 'Opcjonalne',
  'Generic.cancel': 'Anuluj',
  'Generic.next': 'Dalej',
  'Generic.previous': 'Wstecz',
  'Input.roundedValue': 'Potwierdź zaokrąglanie liczb',
  'Item.addToCartButton.label': 'Dodaj',
  'Item.discountCode.fetchError': 'Nie można pobrać kodu rabatowego',
  'Item.discountCode.linkText': 'ÁK',
  'Item.netPrice.fetchError': 'Nie można pobrać ceny netto',
  'Item.netPrice.linkText': 'Net',
  'Item.quantity': 'Ilość',
  'Item.quickviewButton.title': 'Podgląd produktu',
  'Item.remarks.placeholder': 'Twoje referencje',
  'Item.surcharges.totalIncludingSurcharges':
    '{total} Inkl. <surcharges>afgifter</surcharges>',
  'Item.volumeDiscounts.fetchError': 'Nie można pobrać rabatów ilościowych',
  'Item.volumeDiscounts.linkText': 'Net',
  'Item.volumeDiscounts.price': 'Cena',
  'MainNavigation.countryChooser': 'Wybierz swój kraj oraz język',
  'MainNavigation.faq': 'Pomoc',
  'MainNavigation.logIn': 'Zaloguj się',
  'MainNavigation.miniCart': 'Wózki',
  'MainNavigation.myAccount': 'Moje konto',
  'MainNavigation.wishLists': 'Lista życzeń',
  'MiniCart.buttons.create': 'Utwórz',
  'MiniCart.createCartFailedMessage':
    'Wygląda na to, że coś poszło nie tak! Spróbuj ponownie później',
  'MiniCart.new': 'Utwórz nowy',
  'MiniCart.newQuotationText': 'Nazwa',
  'MiniCart.otherCartsTitle': 'Przełącz na',
  'MiniCart.quickOrder': 'Szybkie zamówienie',
  'MiniCart.retrieveCartFailedMessage':
    'Wygląda na to, że coś poszło nie tak... Spróbuj ponownie później',
  'MyAccount.companyName': 'Nazwa firmy',
  'MyAccount.customerId': 'Numer klienta',
  'MyAccount.hideNetPrices': 'Ukryj',
  'MyAccount.logOut': 'Wyloguj',
  'MyAccount.myAccountButton': 'Moje konto',
  'MyAccount.name': 'Nazwa',
  'MyAccount.netPrice': 'Cena netto',
  'MyAccount.retrieveAccountFailedMessage':
    'Wygląda na to, że coś poszło nie tak! Spróbuj ponownie później',
  'MyAccount.showNetPrices': 'Pokaż',
  'MyAccount.username': 'Nazwa użytkownika',
  'NotFoundPage.body':
    'Zrobiliśmy, co w naszej mocy, ale wygląda na to, że ta strona już nie istnieje lub została przeniesiona. Zawsze możesz wrócić do {link} lub użyć funkcji wyszukiwania.',
  'NotFoundPage.body.link': 'Strona główna',
  'NotFoundPage.body.list.1': 'Sprawdź, czy adres URL jest poprawny',
  'NotFoundPage.body.list.2':
    'Czy lista Twoich ulubionych produktów jest nadal ważna?”',
  'NotFoundPage.body.list.3':
    'Spróbuj otworzyć stronę bezpośrednio z poziomu strony głównej firmy Kramp lub menu',
  'NotFoundPage.body.list.4': 'Użyj naszej funkcji wyszukiwania',
  'NotFoundPage.body.list.title': 'Lub wypróbować jedną z następujących opcji:',
  'NotFoundPage.title': 'Nie mogę znaleźć strony, której szukasz',
  'Privacy.private': 'Prywatne',
  'Privacy.shared': 'Wspólne',
  'RecentlyViewed.title': 'Ostatnio oglądane',
  'Search.allCategories': 'All (Wszystkie)',
  'Search.searchInCategory': 'Szukaj w kategorii',
  'Search.queryValidation.nonEmpty': 'Wpisz wyszukiwane hasło',
  'SubCategoryMenu.brandsTitle': 'Marki',
  'SubCategoryMenu.seeAllBrands': 'Wyświetl wszystkie marki',
  'SubCategoryMenu.showAll': 'Pokaż wszystko',
  'UnauthenticatedPage.body':
    'Twoja prośba nie może być zakończona. Nie są one widocznie zalogowany. Spróbuj się zalogować, aby kontynuować.',
  'UnauthenticatedPage.homepageLink': 'Powrót do strony początkowej',
  'UnauthenticatedPage.title': 'Nie są one widocznie zalogowany',
  'WishLists.buttons.create': 'Utwórz',
  'WishLists.buttons.newWishList': 'Nowa lista życzeń',
  'WishLists.createWishListFailedMessage':
    'Wygląda na to, że coś poszło nie tak! Spróbuj ponownie później',
  'WishLists.newWishListText': 'Opis',
  'WishLists.otherWishListsTitle': 'Przełącz na',
  'WishLists.retrieveWishListsFailedMessage':
    'Wygląda na to, że coś poszło nie tak! Spróbuj ponownie później',
};
